### PR TITLE
RFC: My implementation of a body for `Request`

### PR DESCRIPTION
**Pull request by StratusFearMe21**
I went ahead and made the PR of the API I mentioned in #3, So far it works great and is very performant, but I'd still like to know what y'all think about my implementation.

### CODE REVIEW

**Comment by StratusFearMe21** [comment]
I've just added this comment on line 52 of `request.rs` under the `Body`'s `resolve()` function
```
/// This is preferable over using `std::io::Read` if your `Body` is small.
```
I'm pretty sure this is correct, but I'm not 100% sure.

**Comment by Xudong-Huang** [comment]
I like the impl, but could we first make a feature guard to avoid affect the existing project?

**Comment by Xudong-Huang** [comment]
we can first merge the this into dev branch, we would merge it back to mater when matured

**Comment by RoadtogreatWorld** [comment]
Can this already be merged into master? I need to use it and dev branch is so behind.

**Pull request merged**
